services:
  identity-server:
    container_name: unt-voting-identity-server
    build:
      context: ../apps/identity-server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - deepface-service

  vote-server:
    container_name: unt-voting-vote-server
    build:
      context: ../apps/vote-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ../apps/contracts:/app/contracts
    depends_on:
      - postgres
      - redis

  deepface-service:
    container_name: deepface-service
    build:
      context: ../deepface-service
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    container_name: unt-voting-system
    build:
      context: ../apps/frontend
    ports:
      - "80:80"
    depends_on:
      - identity-server
      - vote-server

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data:
